[package]
name = "lib_prime_functions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.3.0"

[lib]
name = "lib_prime_functions"
path = "src/lib.rs"
