name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd rust_euler_suite
        cargo build --verbose --workspace
    - name: Run tests
      run: |
        cd rust_euler_suite
        cargo test --verbose --workspace
